@startuml

class TipoProducto{
    codigo: string
    nombre: string
    impuesto: numeric

}

class Proveedor{
    codigo: string
    nombre: string
}

class Producto{
    codigo: string
    tipo: TipoProducto
    stockdisponible: integer
    stockminimo: integer
    precio: numeric
    proveedor: Proveedor
}

class RespositorioProducto{
    productos: list

    + constructor()
    + crear(producto)
    + editar(producto)
    + eliminar(producto)

}

class CasoUsoProducto{
    respositorioProducto: RespositorioProducto
    + constructor(repositorioProducto)
    + crear(producto)
    + editar(producto)
    + eliminar(producto)

    + presentar()
    + abastecer()
}

Producto --> TipoProducto
Producto --> Proveedor

CasoUsoProducto "1" o-- "0..*" RespositorioProducto
RespositorioProducto --> Producto

@enduml